### ISSUE TITLE
Catch no space left error

### ISSUE THREAD

**Issue by NicoHood** [nims11/IPod-Shuffle-4g#30]
```
Traceback (most recent call last):
  File "/usr/bin/ipod-shuffle-4g", line 739, in <module>
    shuffle.write_database()
  File "/usr/bin/ipod-shuffle-4g", line 631, in write_database
    f.write(self.tunessd.construct())
```

Edit: This happens if the generated voiceover files exceed the space left on the ipod. Affects v1.3

**Comment by NicoHood** [comment]
Fixed here:
https://github.com/nims11/IPod-Shuffle-4g/commit/c0c676c05d09be09807eceea5fbe5daab398232b

BTW: working some more on the script today. You can see the changes so far here:
https://github.com/nims11/IPod-Shuffle-4g/compare/master...NicoHood:version14?expand=1
